name: Build everparse package (windows)
on:
  push:
    branches-ignore:
    - _**
  pull_request:
  workflow_dispatch:
    inputs:
      run_full_ci:
        description: Run full CI
        type: boolean
        default: false

jobs:
  fstar-src:
    ## NOTE: This is copied from build-src in the F* repo.

    runs-on: ubuntu-22.04
    # We prefer slightly older Ubuntu so we get binaries that work on
    # all more recent versions.
    steps:
    - uses: actions/checkout@master
      with:
        path: everparse
        sparse-checkout: |
          opt/Makefile
          opt/hashes.Makefile

    - name: Get F* hash
      run: |
        echo "fstar_hash=$(make -s -C everparse/opt echo-FStar-hash)" >> $GITHUB_ENV

    - uses: actions/checkout@master
      id: checkout
      with:
        repository: FStarLang/FStar
        ref: ${{ env.fstar_hash }}

    - name: Check cache
      id: check-cache
      uses: actions/cache/restore@v4
      with:
        path: fstar-src.tar.gz
        key: FStar-src-${{steps.checkout.outputs.commit}}

    - uses: ocaml/setup-ocaml@v3
      if: steps.check-cache.outputs.cache-hit != 'true'
      with:
        ocaml-compiler: 4.14.2

    - name: Prepare
      if: steps.check-cache.outputs.cache-hit != 'true'
      run: |
        ./.scripts/get_fstar_z3.sh $HOME/bin
        echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
        opam install --deps-only ./fstar.opam

    - name: Set F* version
      if: steps.check-cache.outputs.cache-hit != 'true'
      run: |
        echo FSTAR_VERSION="$(git describe --tags --dirty)" >> $GITHUB_ENV

      # NB: release workflow later adds version number to the name
    - name: Build package
      if: steps.check-cache.outputs.cache-hit != 'true'
      run: |
        eval $(opam env)
        export FSTAR_TAG=
        # ^ no tag in source package
        make -skj$(nproc) package-src ADMIT=1

    - name: Save
      if: steps.check-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: fstar-src.tar.gz
        key: FStar-src-${{steps.checkout.outputs.commit}}

    - uses: actions/upload-artifact@v4
      with:
        path: fstar-src.tar.gz
        name: package-src

  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Workflow succeeded!"
